# Generated by Django 3.1.4 on 2020-12-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_studyelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyelement',
            name='year_in_school_02',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
